### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by vikasraj00**
Added a Description, Fixed Spelling Error

### CODE REVIEW

**Comment by saviomartin** [comment]
@vikasraj00 
You have edited something very small. Do add more content on it. Give more information to the users. 
Also, I can't find the description you have added.

I think these changes are very small and I can just change the type. An issue was better
Or Do add more content to it.

**Comment by vikasraj00** [comment]
> @vikasraj00 
> You have edited something very small. Do add more content on it. Give more information to the users. 
> Also, I can't find the description you have added.
> 
> I think these changes are very small and I can just change the type. An issue was better
> Or Do add more content to it.

I've added the description isn't it visible to you?

**Comment by saviomartin** [comment]
@vikasraj00 

**Oh, I just noticed it now, I have merged, 
Alright, isn't it**

**Comment by vikasraj00** [comment]
Good 👍

**Pull request merged**
